### ISSUE TITLE
Can we show webpack progress?

### ISSUE THREAD

**Issue by ganapativs** [markfinger/webpack-build#15]
Can we add option to show progress? like webpack --progress --colors?

**Comment by markfinger** [comment]
There isn't anything like that in the package itself, but you could use

Webpack's core plugin (which I believe is what --progress does)
https://github.com/webpack/webpack/blob/master/lib/ProgressPlugin.js

Or

Use a 3rd-party plugin
https://www.npmjs.com/package/progress-bar-webpack-plugin

**Comment by ganapativs** [comment]
Thanks. That helps.
