### ISSUE TITLE
CORS support in HMR?

### ISSUE THREAD

**Issue by ganapativs** [markfinger/webpack-build#16]
webpack dev-server can be support CORS with these headers: { "Access-Control-Allow-Origin": "*" } in config, is there anyway to customise webpack-build hmr in config to run on different port from the actual application?

P.S: I am using express server, Getting CORS error because my actual application(running on 8080) and express is running on 3000.

**Comment by markfinger** [comment]
If you're using the CLI, you can set it via the `--port` option.

If that doesn't help, can you provide some more details about your setup?

**Comment by ganapativs** [comment]
My application is in grails which is running at 8080. But my JS part is handled by webpack, which is independently running. Now i want to add hmr using webpack-build. I tried using express server. the hmr server is working, but getting CORS error because 8080 is trying to listen to 8090. So is there any way to add cross origin support for hmr server?

Express file code below:

<pre>
var build = require('webpack-build');
var path = require("path");
var fs = require('fs-extra');
var os = require('os');
var http = require('http');
var express = require('express');
var app = express();
var server = http.Server(app);
build.hmr.addToServer(server);
app.set('port', process.env.PORT || 8090);
// Spawn a worker for every CPU core available
build.workers.spawn(os.cpus().length);
build({
    cache: true,
    cacheDir: path.join(process.cwd(), '.webpack_build_cache'),
    config: path.join(process.cwd(), 'webpack.config.js'),
    watch: true
    hmr: true,
    hmrRoot: 'http://127.0.0.1:' + app.get('port')
}, function(err, data) {
    if(err){
        console.log(err);
    }
    else {
        console.log('Build complete. Watching for changes...');
    }
});
app.listen(app.get('port'));
</pre>

**Comment by markfinger** [comment]
The easiest way is to use a proxy server that points to your grails server, something like https://github.com/nodejitsu/node-http-proxy (or the multitude of other solutions). You might want to check the codebase for webpack's devserver, it has built-in support for that feature.

The idea is that you visit your build server, it traps the specific urls needed for the build and forwards everything else through to the grails server, then returns the response to the client.

**Comment by ganapativs** [comment]
Cool. I'll try that. thanks.
