### ISSUE TITLE
Indicate name change on npm package pages

### ISSUE THREAD

**Issue by bebraw** [markfinger/webpack-build#4]
I noticed npm has four months old version. Perhaps it's time for a bump?

**Comment by markfinger** [comment]
I assume you're coming from npm's webpack-service package - the project was renamed a few months ago when the project's scope started to balloon outside of the original application. Under webpack-build, it's fairly up to date.

Nonetheless, I'll leave this open as an outstanding task to push new versions to npm which make that change explicitly apparent.

Thanks for the heads up, @bebraw

**Comment by bebraw** [comment]
Ah, great. Somehow missed that change. Looking good. :+1:
